/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nico' at '04/05/17 15.40' with Gradle 2.13
 *
 * @author Nico, @date 04/05/17 15.40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
