/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nico' at '09/05/17 14.53' with Gradle 2.13
 *
 * @author Nico, @date 09/05/17 14.53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
